# vtsls 서버 정의
[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]

[language-server.vtsls.config.typescript.inlayHints]
parameterNames = { enabled = "all" }
parameterTypes = { enabled = true }
variableTypes = { enabled = true }
propertyDeclarationTypes = { enabled = true }
functionLikeReturnTypes = { enabled = true }
enumMemberValues = { enabled = true }

# 전역 LSP 설정에서 vtsls를 사용하도록 지정
[[language]]
name = "typescript"
auto-format = true
language-servers = [ "vtsls" ]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "javascript"
auto-format = true
language-servers = [ "vtsls" ]

[[language]]
name = "tsx"
auto-format = true
language-servers = [ "vtsls" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ "vtsls" ]

